### ISSUE TITLE
--debug command-line argument stopped working

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#391]
In the installed version of OpenSesame 3.0.5 on Win7x64 (opensesame_3.0.5-py2.7-win32-1.exe) the --debug argument gives the following error:

Traceback (most recent call last):
  File "opensesame", line 74, in <module>
  File "dist\libqtopensesame\__init__.py", line 27, in <module>
  File "dist\libqtopensesame\items\qtplugin.py", line 23, in <module>
  File "dist\libqtopensesame\items\qtitem.py", line 27, in <module>
  File "dist\libqtopensesame\widgets\item_view_button.py", line 24, in <module>
  File "dist\libqtopensesame\misc\base_subcomponent.py", line 22, in <module>
  File "dist\libqtopensesame\misc\base_component.py", line 26, in <module>
  File "dist\libqtopensesame\misc\base_qtobject.py", line 28, in <module>
ImportError: No module named decorator

I could get it working by moving the file **decorator.pyc** from *C:\Program Files (x86)\OpenSesame3\scipy\misc* to *C:\Program Files (x86)\OpenSesame3\*

I also tried solving this by moving 'decorator' out of the *if jupyter:* in setup-win32.py, but it didn't work.

Development snapshots *opensesame_3.0.6a1-py2.7-win32-1.zip* also has the problem.

**Comment by smathot** [comment]
Should be fixed as of 3.0.6a2.
